import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE_FILE_PATTERN = /\.[jt]sx?$/u;
const TEST_FILE_PATTERN = /\.(?:test|spec)\.[jt]sx?$/u;
const EXCLUDED_SOURCE_SEGMENTS = ["/__tests__/", "/src/test/"];

function fail(message) {
	throw new Error(message);
}

function normalizePath(filePath) {
	return filePath.replaceAll("\\", "/");
}

export function createPaths(repoRoot = process.cwd()) {
	const resolvedRepoRoot = path.resolve(repoRoot);

	return {
		inputFile: path.resolve(resolvedRepoRoot, "locales/en.json"),
		outputFile: path.resolve(resolvedRepoRoot, "src/types/i18n.d.ts"),
		repoRoot: resolvedRepoRoot,
		sourceRoot: path.resolve(resolvedRepoRoot, "src"),
	};
}

export function readCatalog(inputFile) {
	const raw = fs.readFileSync(inputFile, "utf8");
	const parsed = JSON.parse(raw);

	if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") {
		fail(
			"locales/en.json must contain a flat object of string keys and values.",
		);
	}

	for (const [key, value] of Object.entries(parsed)) {
		if (!key.trim()) {
			fail("locales/en.json contains an empty i18n key.");
		}

		if (typeof value !== "string") {
			fail(`locales/en.json value for "${key}" must be a string.`);
		}
	}

	const unsortedKeys = Object.keys(parsed);
	const sortedKeys = [...unsortedKeys].sort((a, b) => a.localeCompare(b));

	if (unsortedKeys.some((key, index) => key !== sortedKeys[index])) {
		fail("locales/en.json keys must stay sorted alphabetically.");
	}

	return parsed;
}

function quoteKey(key) {
	return JSON.stringify(key);
}

export function generateTypes(catalog) {
	const keys = Object.keys(catalog);
	const interfaceBody = keys
		.map((key) => `\t${quoteKey(key)}: string;`)
		.join("\n");

	return `// This file is auto-generated by scripts/manage-i18n.mjs
// Do not edit this file directly.

export interface I18nMessages {
${interfaceBody}
}

export type I18nKey = keyof I18nMessages;
`;
}

function escapeRegExp(value) {
	return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

export function shouldScanSourceFile(filePath, outputFile) {
	const normalizedPath = normalizePath(filePath);
	const normalizedOutputFile = normalizePath(outputFile);

	if (normalizedPath === normalizedOutputFile) {
		return false;
	}

	if (!SOURCE_FILE_PATTERN.test(normalizedPath)) {
		return false;
	}

	if (TEST_FILE_PATTERN.test(normalizedPath)) {
		return false;
	}

	return !EXCLUDED_SOURCE_SEGMENTS.some((segment) =>
		normalizedPath.includes(segment),
	);
}

export function collectSourceFiles(sourceRoot, outputFile) {
	if (!fs.existsSync(sourceRoot)) {
		return [];
	}

	const directories = [sourceRoot];
	const sourceFiles = [];

	while (directories.length > 0) {
		const directory = directories.pop();

		if (!directory) {
			continue;
		}

		for (const entry of fs.readdirSync(directory, {
			withFileTypes: true,
		})) {
			const entryPath = path.join(directory, entry.name);

			if (entry.isDirectory()) {
				directories.push(entryPath);
				continue;
			}

			if (entry.isFile() && shouldScanSourceFile(entryPath, outputFile)) {
				sourceFiles.push(entryPath);
			}
		}
	}

	return sourceFiles.sort((left, right) => left.localeCompare(right));
}

export function markExactKeyUsages(content, usageMap) {
	for (const [key, isUsed] of usageMap.entries()) {
		if (isUsed) {
			continue;
		}

		const keyLiteralRegex = new RegExp(
			`(['"\`])${escapeRegExp(key)}\\1`,
			"u",
		);

		if (keyLiteralRegex.test(content)) {
			usageMap.set(key, true);
		}
	}
}

export function markTemplateLiteralPrefixUsages(content, usageMap) {
	const templateLiteralRegex = /`([^`\n$]*)\$\{[\s\S]*?\}[^`]*`/gu;
	let match = templateLiteralRegex.exec(content);

	while (match) {
		const staticPrefix = match[1];

		if (staticPrefix) {
			for (const [key, isUsed] of usageMap.entries()) {
				if (!isUsed && key.startsWith(staticPrefix)) {
					usageMap.set(key, true);
				}
			}
		}

		match = templateLiteralRegex.exec(content);
	}
}

export function findUnusedKeys(catalog, { outputFile, sourceRoot }) {
	const usageMap = new Map(Object.keys(catalog).map((key) => [key, false]));

	for (const filePath of collectSourceFiles(sourceRoot, outputFile)) {
		const content = fs.readFileSync(filePath, "utf8");
		markExactKeyUsages(content, usageMap);
		markTemplateLiteralPrefixUsages(content, usageMap);

		if ([...usageMap.values()].every(Boolean)) {
			break;
		}
	}

	return [...usageMap.entries()]
		.filter(([, isUsed]) => !isUsed)
		.map(([key]) => key);
}

export function run({ logger = console, repoRoot = process.cwd() } = {}) {
	const {
		inputFile,
		outputFile,
		sourceRoot,
		repoRoot: resolvedRepoRoot,
	} = createPaths(repoRoot);
	const catalog = readCatalog(inputFile);
	const unusedKeys = findUnusedKeys(catalog, { outputFile, sourceRoot });

	if (unusedKeys.length > 0) {
		logger.error("Found unused i18n keys:");

		for (const key of unusedKeys) {
			logger.error(`- ${key}`);
		}

		fail(
			`Unused i18n keys found in ${path.relative(resolvedRepoRoot, inputFile)}.`,
		);
	}

	const fileContent = generateTypes(catalog);
	fs.mkdirSync(path.dirname(outputFile), { recursive: true });
	fs.writeFileSync(outputFile, fileContent, "utf8");
	logger.log(`Generated i18n types at ${outputFile}`);

	return { outputFile, unusedKeys };
}

const entrypointPath = process.argv[1] ? path.resolve(process.argv[1]) : null;

if (entrypointPath && fileURLToPath(import.meta.url) === entrypointPath) {
	try {
		run();
	} catch (error) {
		console.error(error instanceof Error ? error.message : error);
		process.exit(1);
	}
}
